### ISSUE TITLE
data folder

### ISSUE THREAD

**Issue by crislozano** [jvcasillas/morph_pred#1]
No veo la carpeta de data, me imagino que la habrás puesto en .gitignore ¿cómo prefieres que te pase los .csv nuevos con los intérpretes nuevos? No sé muy bien por qué, hay un archivo corrupto, así que tengo (para este proyecto) 10 intérpretes más en lugar de los 11 que recogí.

**Comment by jvcasillas** [comment]
Me parece que no se pudo subir por el tamaño, pero ya no me acuerdo. Podríamos guardar el dataframe como .rds (`saveRDS(df, path = "dataframe.rds")`). Esta función utiliza un algoritmo de compresión y puede que pese menos (en verdad no estoy seguro). Si no, pues lo hacemos como en los viejos tiempos. Mañana estás en el campus?

**Comment by crislozano** [comment]
Sí, pensaba 1 Spring, pero puedo ir al departamento ¿dónde prefieres?

**Comment by jvcasillas** [comment]
Voy a estar en spring street tb.
