### ISSUE TITLE
results BLC

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/morph_pred#10]
@crislozano el documento blc_stats_final.docx está día. No he copiado y pegado nada al google doc porque he respondido a algunos comentarios en las secciones relevantes y no quiero borrar nada antes de que hayáis podido leerlos.

**Comment by crislozano** [comment]
Listo, ya los copié en el google doc. y arreglé un typo directamente en el .Rmd.

**Comment by jvcasillas** [comment]
Perfecto. Voy a añadir dos frases de interpretación directamente en el google (donde has comentado). Añadiré los cambios al .Rmd pero no hace falta copiar y pegar más.
