### ISSUE TITLE
3-way interactions

### ISSUE THREAD

**Issue by crislozano** [jvcasillas/morph_pred#13]
Hola, Joseph:

Me estoy liando con las interacciones. Miré cada variable (wm, pstm, phon freq, biphone) por separado (como único fixed effect) y ninguna sale significativa para ningún grupo. Cuando miro interacciones con WM, sí empiezan a salir cosas significativas, pero no veo cómo se puede interpretar una interacción triple (wm:coda:stress). ¿Sería correcto mirar WM:coda y en otro modelo WM:stress? Para esas sí tengo una hipótesis, que sería con mayor WM mejor predicción en CV y en oxítonas (las más difíciles). 

Gracias,

Cris

**Comment by jvcasillas** [comment]
Hola, 

Lo que propones es justo lo que debes hacer pero en cada nivel del otro factor (en inglés decimos with interactions you "pick a factor of interest and split the other one"... so look at wm:coda at each level of stress... o lo que haga falta para testar tu hipótesis). Sidenote entre tú y yo: esto es buen ejemplo de por qué se debe planificar las hipótesis de antemano, que sean theoretically motived, que no se metan variables porque sí, etc. (ya sé que en este caso no tiene nada que ver contigo, pero creo que es mi responsabilidad enfatizar esto [por tu bien]).  Ea. Me callo. Adelante.

**Comment by crislozano** [comment]
Entiendo, entonces debería filtrar los datos antes de hacer el análisis ¿verdad? Por ejemplo:

filter(stress = "oxytone") y después miro la interacción wm:coda

Ok, estos son 3 millones de análisis, pero me queda claro. Lo que no me queda claro es que pasa cuando añado `group`. Porque ahí...ya vuelvo a 1million-way interaction. ¿Lo dejaría solo en los análisis individuales?

Y...ya, lo sé, esto es un lío, te controlan los datos a ti, no tú a los datos. Ahora cuando vuelva ella de la playa le hablaré del proyecto nuevo que quiere hacer porque...con este plan yo no quiero seguir.

**Comment by jvcasillas** [comment]
Perdona que haya tardado. 

> Entiendo, entonces debería filtrar los datos antes de hacer el análisis ¿verdad? Por ejemplo:
> filter(stress = "oxytone") y después miro la interacción wm:coda

Sí. 

> Ok, estos son 3 millones de análisis, pero me queda claro. Lo que no me queda claro es que pasa cuando añado group. Porque ahí...ya vuelvo a 1million-way interaction. ¿Lo dejaría solo en los análisis individuales?

Mira... sugiero que le preguntes a Nuria qué quiere que hagas. Me parece que se te va de las manos (cómo vas a interpretar una 4-way interaction?). Es más de lo que te comento arriba. O sea, tienes una idea de cómo lo veo... lo que diga ella.

**Comment by crislozano** [comment]
Hablé con ella hace un rato, me dijo que está bien si no añadimos grupo para que no haya una interacción cuádruple, y que haga lo mismo que hice para WM con phonotactic y con lexical frequency. ¿Cómo de factible ves reportar los resultados? Me da miedo que necesite 10 páginas solo para resultados. La idea es mandarlo a Language Learning, que tiene 10.000 palabras de límite.

**Comment by jvcasillas** [comment]
Buena pregunta. Dependerá de lo que salga, supongo. Language Learning te dice 10k al principio pero luego te dejan subir hasta 13k. Al menos ha sido mi experiencia con ellos. Puedes hacer lo típico de decir que solo vas a reportar cosas significativas y luego usar su online repository para poner todas las tablas. Quizá sea posible así.

**Comment by crislozano** [comment]
Hola de nuevo, ya tengo las tres variables medidas pero ahora me estoy liando para hacer las tablas ¿podríamos quedar esta semana? Estuve hoy hablando con Nuria y queremos enviar este artículo para el 15 de agosto. Esta semana (para el domingo) le pasaré el borrador hasta resultados.

**Comment by jvcasillas** [comment]
Me voy mañana de viaje. No te puedo ayudar por aquí?

**Comment by jvcasillas** [comment]
Me dice Nuria que estoy en este artículo como co-autor... creía que no, que habíamos decidido que lo hacíais vosotras... por eso no me he involucrado mucho y te he dicho que hables con ella sobre las decisiones metodológicas (re: las interacciones). Cuando vuelva reviso es script y todo lo que has estado haciendo más a fondo. Mientras tanto puedes poner problemas/preguntas específicas aquí?

**Comment by jvcasillas** [comment]
Tb recomiendo que hagas tus cambios en un branch especifico (por ejemplo uno que se llame lang_learning) para no liarla con los otros cambios que estoy haciendo (recuerdas lo de "never commit to master" de clase? [si estás trabajando con varias personas]).

**Comment by crislozano** [comment]
Ok, crearé un branch...porque creo que ya la lié guardando los modelos. ¿Cuándo vuelves? Voy a escribir antes y por la tarde me pondré con ello y ya te envío las preguntas.

**Comment by crislozano** [comment]
Ya creé el branch. Tengo preguntas en varios frentes:

1. Guardar los modelos: estuve tiempo pensando cómo funcionaba la estructura y creo que ya llegué a guardarlos de manera programática. Pero no me queda claro para qué es esto

```
# Save models predictions
  model_preds <- mget(c("fits_all", "target_offset_preds"))

  save(model_preds,
       file = here("models", "stress", "s3_adv_int_nat", "eye_track", "gca",
                   "model_preds.Rdata"))
```

2. Fui pasando todos los modelos y viendo la función ANOVA sé si hay algo significativo, pero para interpretarlo necesito llegar a la tabla y ahí sí que me pierdo con toda la estructura ¿tengo alguna manera más sencilla de conseguir la info? (aunque...en realidad sé que debería aprender a hacer la tabla porque la necesitaremos para el paper)

3. No veo claro cómo puedo hacer los gráficos (para interpretar los datos) con variables continuas. Es decir, con stress, entiendo que vamos a compara la curva de paroxytone con la de oxytone, pero....¿qué pasa si es WM?¿qué comparo?

**Comment by jvcasillas** [comment]
> Ya creé el branch. Tengo preguntas en varios frentes:
> 
> 1. Guardar los modelos: estuve tiempo pensando cómo funcionaba la estructura y creo que ya llegué a guardarlos de manera programática. Pero no me queda claro para qué es esto
> 
> ```
> # Save models predictions
>   model_preds <- mget(c("fits_all", "target_offset_preds"))
> 
>   save(model_preds,
>        file = here("models", "stress", "s3_adv_int_nat", "eye_track", "gca",
>                    "model_preds.Rdata"))
> ```
> 

Esto guarda las predicciones que estima el modelo en un archivo aparte. Se usan luego para los gráficos. 


> 1. Fui pasando todos los modelos y viendo la función ANOVA sé si hay algo significativo, pero para interpretarlo necesito llegar a la tabla y ahí sí que me pierdo con toda la estructura ¿tengo alguna manera más sencilla de conseguir la info? (aunque...en realidad sé que debería aprender a hacer la tabla porque la necesitaremos para el paper)

La info siempre viene de summary(mod), o sea aunque no puedas hacer la tabla (ahora) deberías tener acceso a la información necesaria (o es que no te entiendo). Podemos mirarlo de la tabla este finde si quieres. He decidido esta mañana que no voy de viaje así que estoy por aquí. 

> 2. No veo claro cómo puedo hacer los gráficos (para interpretar los datos) con variables continuas. Es decir, con stress, entiendo que vamos a compara la curva de paroxytone con la de oxytone, pero....¿qué pasa si es WM?¿qué comparo?

Esto supone un problema un poco más chungo... es que son muchas variables (aquí normalmente pondría mis quejas de siempre pero me las guardo). Una posibilidad sería hacer triptych plots como hicimos en el trabajo que mandamos a SSLA.

**Comment by crislozano** [comment]
Ok, ¿cuándo te viene bien?

**Comment by jvcasillas** [comment]
¿Qué tal el domingo? A las 2 o 3?

**Comment by crislozano** [comment]
¿podría ser antes? Tenía pensado ir a algún lado el domingo por la tarde. Mañana estaré también por aquí hasta las 6 approx. y hoy a cualquier hora

**Comment by jvcasillas** [comment]
Entonces habrá que intentar hacerlo por internet. A ver si entiendo el problema. Ya has terminado de "fit" todos los modelos y quieres crear una tabla con todo? Puedo echar un vistazo a tu branch pero necesito saber qué se debería incluir. Cuáles son los archivos que estás usando?

**Comment by jvcasillas** [comment]
Otra cosa... ayer dijiste que la habías liado intentando guardar los modelos y luego lo arreglaste. Lo que has arreglado está en el master? Están los modelos de antes (el articulos de BLC)?

**Comment by crislozano** [comment]
Sí, acabo de revisarlo y están ahí. Al principio hice una copia del script de GCA y empecé a añadir todo ahí (incluidos los modelos), después me di cuenta de que se me iba de las manos y lo dividí en 3 scripts más, guardando los modelos por separado. Me di cuenta del lío antes de hacer el commit, así que no fue tan grave. 

Acabo de terminar de guardar todos los modelos. Están listos ind_mods para cada variable (wm, phon, lex freq) y sus respectivos anovas. Pero no sé qué modelo me haría falta aquí (en el código de abajo) para los gráficos, las tablas y poder guardar model_preds:

```
fits_all <- predictSE(gca_full_mod_int_3, new_dat_all) %>%
  as_tibble %>%
  bind_cols(new_dat_all) %>%
  rename(se = se.fit) %>%
  mutate(ymin = fit - se, ymax = fit + se,
         group = fct_recode(group, M = "ss", NIN = "la", IN = "int"))

```
En lugar de `gca_full_mod_int_3` ¿cuál debería poner?

Los 3 scripts nuevos están en ⁨scripts⁩ ▸ ⁨stress⁩ ▸ ⁨s3_adv_int_nat⁩ ▸ ⁨eye_track⁩. Son el 07, 08 y 09. (en el branch lang_learning)

**Comment by jvcasillas** [comment]
Intento entender lo que has hecho con respecto a los modelos antiguos. Veo que en `lang_learning` y en `master` los modelos `full_mods.Rdata`, `ind_mods.Rdata`, `model_preds.Rdata` y `nested_model_comparisons.Rdata` se han modificado (hace 5 días en el caso de lang_learning y 15 en el caso de master). Estás segura de que no ha habido cambios ahí? Puedo recuperar los modelos anteriores por si acaso. Creo que deberíamos separar lo que es de BLC y lo que es de LL. Será más fácil ahora que hay un branch nuevo. 

Pon tus modelos nuevos dentro de 
`morph_pred/models/stress/s3_adv_int_nat/eye_track/gca/lang_learning` y el branch `lang_learning`. 

Cuando esté todo terminado pondré los modelos antiguos dentro de 
`morph_pred/models/stress/s3_adv_int_nat/eye_track/gca/blc`. 

Ahora me pondré a mirar cómo has hecho el análisis a ver si puedo responder tu pregunta de arriba mejor.

**Comment by jvcasillas** [comment]
> ```
> fits_all <- predictSE(gca_full_mod_int_3, new_dat_all) %>%
>   as_tibble %>%
>   bind_cols(new_dat_all) %>%
>   rename(se = se.fit) %>%
>   mutate(ymin = fit - se, ymax = fit + se,
>          group = fct_recode(group, M = "ss", NIN = "la", IN = "int"))
> ```
> 
> En lugar de `gca_full_mod_int_3` ¿cuál debería poner?
> 


Tienes que poner el mejor modelo según lo que haya salido en los model comparisons. ¿Por qué has hecho wm, phon_freq y lex_freq en modelos y scripts diferentes? 

Me parece que tu model comparison debería estar en un script. Estableces el base model y vas añadiendo todo de WM (como has hecho). Te quedas con el mejor modelo y vas añadiendo phon_freq. Te quedas con el mejor y vas añadiendo lex_freq. Te quedas con el mejor y usas ese modelo para las predicciones y para generar la tabla. Ahora habría que pensar en el order of entry (he dicho wm > phon_freq > lex_freq porque están en ese orden en los scripts). Tiene sentido?

**Comment by crislozano** [comment]
Pero eso sumado a lo que ya había (cosa+stress), ¿no es demasiado? ¿Estarás
mañana por 1 spring o AB?

**Comment by jvcasillas** [comment]
Sí, en teoría es demasiado (de ahí mis comentarios anteriores). A lo mejor el modelo final no incluye todo (si añades algo y no mejora el fit, si quita).

**Comment by jvcasillas** [comment]
Ah y sí, mañana estoy en spring street.

**Comment by crislozano** [comment]
A qué hora podríamos vernos?

**Comment by jvcasillas** [comment]
Cualquier hora a partir de las 9.

**Comment by crislozano** [comment]
Ya probé a añadir las tres variables al modelo más complejo que había en `03_analysis_gca` y ninguna sale significativa. La duda que tengo ahora es, no son significativas como main effect ¿pero podría haber interacciones, no? (está actualizado todo en el script nuevo, guardé los modelos en un archivo nuevo: `full_mods_lang_learn`)

**Comment by jvcasillas** [comment]
Creo que no has hecho commit y push con los cambios que hiciste (no los veo), pero efectivamente. Puede haber interacciones. Las testas igual que has hecho con los otros nested model comparisons.

**Comment by jvcasillas** [comment]
Mentira... acabo de ver que lo has hecho en el script original. Creo que deberías hablar con Nuria antes de testar todas las interacciones. A ver si podéis determinar algo que tenga sentido. Creo que deberías meter group (me refiero a todas las posibles interacciones que involucren el factor group). A partir de ahí es todo fishing.

**Comment by crislozano** [comment]
Ok, hablaré con ella. ¿Cómo sería la estructura de "todas las posibles interacciones que involucren el factor group"?
Por ejemplo:
coda + stress + wm:group

**Comment by jvcasillas** [comment]
Así es. Otra opción es fit el modelo máximo primero para ver todos los parámetros que estima y luego añadirlos uno a uno (va a ser una bararidad). Algo tipo `ot1 * ot2 * ot3 * coda * stress * group * wm * lex` etc.

**Comment by crislozano** [comment]
Las interacciones grupo por grupo con WM están en scripts>stress>s3_adv_int_nat>eye_track>07_analysis_gca_wm.R (lang_learning branch)
Fui poniendo el output de las comparaciones de los modelos en comentarios.
Para interpretarlo ahora tengo 2 problemas:
1. ¿Cómo saco los gráficos? Creo que este problema ya te lo había comentado, porque como es una variable contínua...Nuria me dijo que si era un problema, que la hiciese categórica con un median split
2. Estuve mirando el tutorial de pretty_tables de Tristan Mahr, pero me lío entre las funciones que tienes el script de helpers y la sintaxis para la tabla en el informe. ¿Qué me recomiendas?

**Comment by jvcasillas** [comment]
> Las interacciones grupo por grupo con WM están en scripts>stress>s3_adv_int_nat>eye_track>07_analysis_gca_wm.R (lang_learning branch)
> Fui poniendo el output de las comparaciones de los modelos en comentarios.
> Para interpretarlo ahora tengo 2 problemas:
> 
> 1. ¿Cómo saco los gráficos? Creo que este problema ya te lo había comentado, porque como es una variable contínua...Nuria me dijo que si era un problema, que la hiciese categórica con un median split

No recomiendo que hagas median split (qué significa con una variable estandarizada?). Sigo pensando que lo mejor sería un plot triptych (o marginal effects plots). Si ya tienes el modelo final podemos usar la función que tenemos que sacar las predicciones del modelo (no recuerdo cómo se llama ahora mismo) para sacar predicciones con la variable WM fijada -1, 0 y 1. Es algo que se hace con mucha frecuencia. 


> 2. Estuve mirando el tutorial de pretty_tables de Tristan Mahr, pero me lío entre las funciones que tienes el script de helpers y la sintaxis para la tabla en el informe. ¿Qué me recomiendas?

No te puedo aconsejar porque ni me acuerdo de todo ese código. Si ya tienes el modelo final, avisa (dime cuál es) y la saco yo.

**Comment by crislozano** [comment]
¿Cómo decido cuál es el modelo final? Probé muchas combinaciones, pero las interacciones que tengo son en los modelos individuales.

**Comment by jvcasillas** [comment]
> ¿Cómo decido cuál es el modelo final? Probé muchas combinaciones, pero las interacciones que tengo son en los modelos individuales.

Recuerda que los modelos individuales están para ayudarte a interpretar el modelo principal (el que tiene el factor group). No se usan para los gráficos. Decides cuál es el modelo final como siempre... empiezas con el modelo null y vas añadiendo predictores. Si mejora el fit, se queda. Si no, se elimina. Así sucesivamente hasta terminar de probar todo. El modelo final es el último que mejore el fit (no necesariamente el último que ejecutes). Puedes empezar con el último del paper de BLC. Vas añadiendo wm... o la variable que hayas escogido 😂

**Comment by crislozano** [comment]
Pero así no me sale nada, ninguna de las variables mejora el fit.

**Comment by jvcasillas** [comment]
Cómo que ninguna? O quieres decir ninguna de las nuevas? Has testado todas las interacciones y ninguna ha salido significativa?

**Comment by crislozano** [comment]
Para testarlas sería algo como:
Stress + group + coda:wm
Stress + coda+ group:wm
coda + group + stress:wm

**Comment by jvcasillas** [comment]
Empezarías así...

```
# add wm effect to intercept, linear slope, quadratic, and cubic time terms
new_mod_0 <- update(final_mod_from_blc,    . ~ . + wm)
new_mod_1 <- update(new_mod_0, . ~ . + ot1:wm)
new_mod_2 <- update(new_mod_1, . ~ . + ot2:wm)
new_mod_3 <- update(new_mod_2, . ~ . + ot3:wm)
```

Luego tienes que añadir los 2/3-way...

```
# add wm effect to intercept, linear slope, quadratic, and cubic time terms
new_mod_4 <- update(new_mod_3,    . ~ . + wm:group)
new_mod_5 <- update(new_mod_4, . ~ . + ot1:wm:group)
new_mod_6 <- update(new_mod_5 . ~ . + ot2:wm:group)
new_mod_7 <- update(new_mod_6, . ~ . + ot3:wm:group)
```

Luego 4/5-way... hasta testarlo todo (insert annoying comment complaining about adding too many factors here). Tiene sentido?

**Comment by crislozano** [comment]
Listo, el modelo más completo del script `03_analysis_gca.R` es `gca_wm_coda_mod_int_3` (línea 401 del script)

**Comment by jvcasillas** [comment]
Espera... por qué lo has hecho en ` 03_analysis_gca.R` y no en `07_analysis_gca_wm.R`?

**Comment by crislozano** [comment]
En ’07_analysis_gca_wm.R’ están los modelos individuales, ¿lo muevo? (creo que no tengo un motivo de peso para ponerlo en un sitio u otro.

**Comment by jvcasillas** [comment]
A ver... la idea es de mantener separado lo que es de BLC y LL. Como el análisis de LL se basa en el de BLC puedes empezar con el último modelo de BLC. O sea no tienes que repetir todo el código de `03_analysis_gca.R`... puedes cargar los modelos (o cómo se diga) y empezar con lo nuevo. Es mejor así porque vamos a tener que crear archivos nuevos para varias cosas (los model preds, por ejemplo) y tampoco quiero que se borren las cosas de BLC. Pasa lo mismo con el report para los resultados. Habrá que crear otra carpeta `ll` (o lo que sea) en el directorio "reports > stress" para no borrar el antiguo. Me explico?

**Comment by crislozano** [comment]
Ok, ahora lo cambio, te aviso en cuanto esté listo.

**Comment by crislozano** [comment]
Listo, ya está todo en el script 07_analysis_gca_wm.R  (full models + individual models for interpreting results)

**Comment by jvcasillas** [comment]
Ok. He actualizado `07_analysis_gca_wm.R` y he creado `10_plots_gca_wm.R`. Lo de los gráficos es complicado. Podemos hablar a ver si tienes sugerencias pero creo que la idea básica va a funcionar. Tendremos dos series de gráficos. Gráfico 1 es para entender el efecto de WM y el efecto de coda/stress en cada grupo. Gráfico 2 es para entender las diferencias entre los grupos, por lo que utiliza las predicciones del modelo controlando wm (holding it at the group mean). Los adjunto aquí para que los veas. 

![stress_p1](https://user-images.githubusercontent.com/1747068/63214940-24482200-c0ed-11e9-9558-3d5ddde8eb67.png)
![stress_p2](https://user-images.githubusercontent.com/1747068/63214967-97519880-c0ed-11e9-9e27-1c97b8db47a5.png)

**Comment by jvcasillas** [comment]
Esta tarde me pongo con la tabla.

**Comment by crislozano** [comment]
Ok, gracias

**Comment by jvcasillas** [comment]
Si vas a trabajar en algo del lang_learning branch recuerda que tienes que pull in los cambios antes.

**Comment by crislozano** [comment]
Vi que está la tabla :-) ¿Te parece si hago un doc para interpretar las interacciones como me enseñaste y tú verificas que no me esté inventando cosas?

**Comment by jvcasillas** [comment]
No creo que haga falta crear otro doc. Hazlo en el archivo donde est'a la tabla.

**Comment by jvcasillas** [comment]
@crislozano había 4-way interactions en los nested model comparisons? Si no, puede que esto acabe siendo más fácil de lo que creíamos (por no haber incluido lex freq y phon freq).

**Comment by crislozano** [comment]
Nop, solo 3-way. Pero WM solo sale para los nativos. Otra cosa que me
extraña es que los efectos varían en comparación con BLC. Por ejemplo, si
antes lexical stress salía en quadratic time term, ahora sale en quadratic
y cubic. ¿Tiene sentido esto?

**Comment by jvcasillas** [comment]
Entonces no creo que vayas a tener todos los subsets... eso era principalmente si hab'ia 4-way. Cu'al es el 3-way? Con respecto a los resultados de BLC, s'i tiene sentido porque ese estudio no controla wm. O sea puede cambiar si es un factor relevante (y parece que lo es).

**Comment by crislozano** [comment]
Acabo de subir la descripción cualitativa del gráfico `reports/stress/lang_learn/language_learning_stats.Rmd ` Creo que de lo que no estoy segura es cómo interpretarlo cuando las curvas de CV y CVC parece que muestran una interacción (se cruzan).  ¿Le echas un vistazo antes de que lo vea Nuria o se lo paso así?

**Comment by crislozano** [comment]
¡Ah! y una duda que me acaba de surgir. WM es algo que depende de los participante, pero Phonotactic Frequency depende del target, para el gráfico eso da igual ¿verdad? Me hizo replantearme si habría que cambiar algo de cómo está programado el gráfico (y no sé si me estoy explicando bien...)

**Comment by jvcasillas** [comment]
Ahora le echo un vistazo. En cuanto a la segunda pregunta, no creo que importe, pero lo voy a pensar un poco m'as.

**Comment by jvcasillas** [comment]
Está bastante bien. La cosa ahora es cómo interpretar las interacciones. En algunos casos ocurren después de 200ms, por lo que no creo que nos interesen, pero el hecho de que low wm esté por encima en CVC... bueno a ver qué dice Nuria. En fin, bien hecho. Muy fácil de seguir. Creo que es justo lo que quería. No has actualizado el .docx, no? He hecho pull para coger los cambios nuevos pero sólo los veo en el documento .Rmd.

**Comment by crislozano** [comment]
Oops, no, se me olvidó darle a knit para que actualizase el .docx 
Ahora lo hago. Todavía no está en el departamento, Laura quedó con ella a las 3, a ver qué dice.

**Comment by crislozano** [comment]
Me da un error una de las tablas, creo que porque cambiamos el modelo final (añadimos alguna interacción, y sacamos un gráfico diferente). Mejor esperar a ver qué dice Nuria para arreglarlo, ¿no?

**Comment by jvcasillas** [comment]
No te preocupes. Lo arreglo después de que hables con ella.
