### ISSUE TITLE
time adjustment

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/morph_pred#2]
Me voy a poner a mirar los datos ahora. Recuérdame cuánto había que ajustar el time course. Sé que lo comentamos en algún momento y no dejé apuntes en el script. Ahora resta 20 bins (20 x 10 = 200ms), pero había que incluir la información del principio de la grabación... me parece que usamos 26 pero es que fue hace mucho tiempo. Te acuerdas?

**Comment by crislozano** [comment]
Extraje los datos a partir de audio onset, entonces es solo 200ms (no hay que preocuparse por la fase familiarización, ni fixation point time, ni nada de eso).

**Comment by jvcasillas** [comment]
Perfecto. Gracias.
