### ISSUE TITLE
GCA issue

### ISSUE THREAD

**Issue by crislozano** [jvcasillas/morph_pred#8]
Acabo de probar si edad tiene un efecto con los no intérpretes y me sale lo mismo (no hay efecto de edad), pero también me sale este mensaje y no sé si es que no converge:

> boundary (singular) fit: see ?isSingular

Probé con lo que tú sacaste y sale el mismo mensaje.

**Comment by jvcasillas** [comment]
Sí, me fijé en eso el otro día haciendo un tutorial (no relacionado). Singular fit y convergence son dos cosas distintas. Normalmente si tienes un singular fit tiene que ver con la cantidad de parámetros que el modelo "fits". Al parecer en este case se trata de una actualización de `lme4`. Da avisos más libremente ahora. No creo que tengamos singular fit y estoy pendiente de si esto cambia en las próximas actualizaciones. También he vuelto a ejecutar todos los ejemplos del libro de GCA y también dan singular fit. O sea si realmente hay un problema lo tenemos todos, pero en realidad no creo que sea nada grave.

**Comment by crislozano** [comment]
Perfecto. Nuria me pasó las edades de los monolingües, todavía no lo actualicé porque faltaba uno. ¿Está bien mirar cada grupo por separado o supone algún problema?

**Comment by jvcasillas** [comment]
No creo que suponga ningún problema, pero dudo que sea necesario a no ser que los monolingües sean muy mayores también. For the sake of completeness, vale.
